---
title: "P8105_HW2_bz2561"
author: "Bohan Zhu"
date: "2025-09-23"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy = TRUE)
```

```{r}
library(tidyverse)
```

## Problem 1

Import `pols_month`

```{r}
pols_month_df =
  read_csv("data/fivethirtyeight/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day")) |> 
  mutate(
    month = month (
      as.integer(month),
      label = TRUE,
      abbr = FALSE
    )
  ) |> 
  pivot_longer(
    cols = c(prez_gop, prez_dem),
    names_to = "president",
    values_to = "party"
  ) |> 
  select(-day)
```

Import `snp`

```{r}
snp_df =
  read_csv("data/fivethirtyeight/snp.csv") |> 
  janitor::clean_names() |> 
  mutate(date = as.Date(date, format = "%m/%d/%y")) |> 
  separate(date, into = c("year", "month", "day")) |> 
  mutate(
    month = month (
      as.integer(month),
      label = TRUE,
      abbr = FALSE
    )
  ) |> 
  select(-day) |> 
  relocate(year,everything()) |> 
  arrange(year,month)
```

Import `unemployment`

```{r}
unemployment_df =
  read_csv("data/fivethirtyeight/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    cols = jan:dec,
    names_to = "month",
    values_to = "unemployment_percentage"
  ) |> 
 mutate(
   month =
     month(
       parse_date_time(month, orders = "b"),
       label = TRUE,
       abbr = FALSE
     )
 )
```

